name: media-server

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - UGID=1000
      - TZ=Europe/Istanbul
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - ./docker/transmission/config:/config
      - /home/yunus/Downloads/transmission:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=hcaptcha-solver

  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./docker/radarr/config:/config
      - /media/yunus/4tb/media:/data
      - /home/yunus/Downloads/transmission:/downloads
    depends_on:
      - transmission
      - prowlarr
    ports:
      - 7878:7878

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./docker/sonarr/config:/config
      - /media/yunus/4tb/media:/data
      - /home/yunus/Downloads/transmission:/downloads
    depends_on:
      - transmission
      - prowlarr
    ports:
      - 8989:8989
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./docker/prowlarr/config:/config
    ports:
      - 9696:9696
    depends_on:
      - flaresolverr

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - ./docker/recyclarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./docker/jellyfin/library:/config
      - /media/yunus/4tb/media:/data
    ports:
      - "8096:8096"

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - transmission
      - flaresolverr
      - radarr
      - sonarr
      - prowlarr
      - jellyfin

volumes:
  caddy_data:
  caddy_config:
