name: media-server

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - UGID=1000
      - TZ=Europe/London
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - ./docker/transmission/config:/config
      - "D:\\data\\downloads:/downloads"
    ports:
      - 9091:9091
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=hcaptcha-solver

  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker/radarr/config:/config
      - "D:\\data:/data"
    depends_on:
      - transmission
      - prowlarr
    ports:
      - 7878:7878

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker/sonarr/config:/config
      - "D:\\data:/data"
    depends_on:
      - transmission
      - prowlarr
    ports:
      - 8989:8989
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker/prowlarr/config:/config
    ports:
      - 9696:9696
    depends_on:
      - flaresolverr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./docker/bazarr/config:/config
      - "D:\\data:/data"
    ports:
      - 6767:6767

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - transmission
      - flaresolverr
      - radarr
      - sonarr
      - prowlarr
      - bazarr

volumes:
  caddy_data:
  caddy_config: